### ISSUE TITLE
Exercise 1 Task 2, Notebook 03 Deploy as Web Service, issue in cmd 15 is failing

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Big-data-and-visualization#54]
Showing error, no such file or directory, it was all good last week. 

cat: /databricks/driver/aml_config/config.json: No such file or directory

Please look into this ASAP, we've workshop today itself.

Thanks
Abhishek Pathania

**Comment by joelhulen** [comment]
I have updated the Databricks notebook file. It is available to download now.

**Comment by Abhishekpathania01** [comment]
Thanks @joelhulen for fix this, but it is not yet updated in the HTML Lab guide, can you please fix the same there, we need to provide HTML lab  guide to users for upcoming workshops.

Thanks,
Abhishek

**Comment by joelhulen** [comment]
@Abhishekpathania01 There is nothing to update in the HTML Lab guide. The instructions are located within the Databricks notebook I updated. Since I overwrote the .DBC file, there are no changes to the import link.

I've fixed cmd 13 by uncommenting line 10.

**Comment by akn9050** [comment]
Hi @joelhulen, we have seen notebook **BigDataVis.dbc** in  **03 Deploy as Web Service** is still showing **aml_config = ‘aml_config’** in cmd 13, 15 and 26. It should be changed to **aml_config = ‘.azureml’** 

Can you please do required changes in notebook 03.
Required Changes==>
Notebook  **BigDataVis.dbc** 03 Deploy as Web Service
In cmd 13 line 10, from **aml_config = ‘aml_config’** to **aml_config = ‘.azureml’**
In cmd 15 line 2, from **cat /databricks/driver/aml_config/config.json** to **cat /databricks/driver/. azureml /config.json**
In cmd 26 line 4, from **aml_config = '/azureml'**  to  **aml_config = '.azureml'**
