### ISSUE TITLE
Deploy for batch scoring error

### ISSUE THREAD

**Issue by GautamRaviKumar** [microsoft/MCW-Big-data-and-visualization#98]
Running this notebook at the end of the batch score notebook( via Data Factory Pipeline) at this point:
prediction.write.mode("overwrite").saveAsTable("scoredflights")

Gives this error:
org.apache.spark.SparkException: Job aborted.

Expanding the error gives:
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-2335063144313085> in <module>
----> 1 prediction.write.mode("overwrite").saveAsTable("scoredflights")

/databricks/spark/python/pyspark/sql/readwriter.py in saveAsTable(self, name, format, mode, partitionBy, **options)
    776         if format is not None:
    777             self.format(format)
--> 778         self._jwrite.saveAsTable(name)
    779 
    780     @since(1.4)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o873.saveAsTable.
: org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:201)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:201)
	at org.apache.spark.sql.execution.datasources.DataSource.writeAndRead(DataSource.scala:559)
	at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.saveDataIntoTable(createDataSourceTables.scala:216)
	at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:175)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:108)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:106)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:126)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:140)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$5.apply(SparkPlan.scala:193)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:189)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:140)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:117)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:115)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:711)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:711)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:113)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:243)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:99)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:173)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:711)
	at org.apache.spark.sql.DataFrameWriter.createTable(DataFrameWriter.scala:509)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:488)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 36.0 failed 4 times, most recent failure: Lost task 1.3 in stage 36.0 (TID 51, 10.139.64.4, executor 0): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$9: (string) => double)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:640)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:235)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:172)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)
	at org.apache.spark.scheduler.Task.run(Task.scala:113)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:537)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:543)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Unseen label: 2013.  To handle unseen labels, set Param handleInvalid to keep.
	at org.apache.spark.ml.feature.StringIndexerModel$$anonfun$9.apply(StringIndexer.scala:261)
	at org.apache.spark.ml.feature.StringIndexerModel$$anonfun$9.apply(StringIndexer.scala:247)
	... 15 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2362)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2350)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2349)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2349)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2582)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2529)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2517)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:897)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2282)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:170)
	... 36 more
Caused by: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$9: (string) => double)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:640)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:235)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:172)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)
	at org.apache.spark.scheduler.Task.run(Task.scala:113)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:537)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:543)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: org.apache.spark.SparkException: Unseen label: 2013.  To handle unseen labels, set Param handleInvalid to keep.
	at org.apache.spark.ml.feature.StringIndexerModel$$anonfun$9.apply(StringIndexer.scala:261)
	at org.apache.spark.ml.feature.StringIndexerModel$$anonfun$9.apply(StringIndexer.scala:247)
	... 15 more

**Comment by feaselkl** [comment]
@GautamRaviKumar I was able to execute the notebook `01 Deploy for Batch Scoring` successfully.  Based on the error message, it looks like there might have been an issue converting from string to double, which makes me think something was configured not quite correctly.

The first thing to check is whether there is a `default.scoredflights` table.  My completed version looks like:

| |col_name|data_type|
|-|----------|-----------|
|1|OriginAirportCode|string|
|2|Month|int|
|3|DayOfMonth|int|
|4|CRSDepHour|int|
|5|DayOfWeek|int|
|6|Carrier|string|
|7|DestAirportCode|string|
|8|DepDel15|int|
|9|WindSpeed|double|
|10|SeaLevelPressure|double|
|11|HourlyPrecip|double|
|12|OriginAirportCodeIndex|double|
|13|OriginAirportCodeclassVec|vector|
|14|CarrierIndex|double|
|15|CarrierclassVec|vector|
|16|DestAirportCodeIndex|double|
|17|DestAirportCodeclassVec|vector|
|18|label|double|
|19|features|vector|
|20|rawPrediction|vector|
|21|probability|vector|
|22|prediction|double|

Is it possible that you have a schema which differs from this?  You might want to drop the `default.scoredflights` table if you have one and see if that fixes the problem.

Also, was the `windowStart` parameter for executing the pipeline set to 3/1/2017?

Those are the most likely causes I can think of, but I would recommend going back through the configuration steps in Exercise 5 and ensuring that everything is set up correctly.

**Comment by timahenning** [comment]
Hi @GautamRaviKumar, did the recommendation work?  Let us know.

Tim

**Comment by GautamRaviKumar** [comment]
Hi,
Not sure what to do or where to check

**Comment by GautamRaviKumar** [comment]
Like where the default.scoredflights table is.
But I definitely set the pipeline to 3/1/2017

Thanks for helping,
Gautam

**Comment by feaselkl** [comment]
That would be a Databricks table.  You can see them in the Databricks workspace by selecting the Data menu option.  That will open the Databases pane and then the Tables pane, where you should see any tables that you've created.  You will need a running Databricks cluster to see any databases or tables.

My recommendation for what you should do is to check for the existence of that table first and delete it if it does exist.  Then, go back through the steps in exercise 5 to ensure that everything is set up correctly.  I've confirmed that exercise 5 will work when everything is set up correctly

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with the above instructions given.  If you are still having trouble, please reopen the issue.

**Comment by aniturza** [comment]
Hi! I've just run the notebook and I face the same problem. I re-started several times but the problem persists when running 
`prediction.write.mode("overwrite").saveAsTable("scoredflights")`. The error is exactly the same as https://github.com/microsoft/MCW-Big-data-and-visualization/issues/98#issue-963196411 . Any help, please?

**Comment by feaselkl** [comment]
@aniturza 

Do you have a default.scoredflights table?  Does its schema look like the one in my comment above?  If the schema differs, drop that table and try again.

Was the windowStart parameter for executing the pipeline set to 3/1/2017?

**Comment by aniturza** [comment]
@feaselkl the table default.scoredflights has not been created, but prediction dataframe columns and types are the same as the ones you sent here https://github.com/microsoft/MCW-Big-data-and-visualization/issues/98#issuecomment-896905905

**Comment by feaselkl** [comment]
Okay.  There are three possible issues I can foresee.

1. When you set up the windowStart parameter on ADF, can you confirm that it's "3/1/2017"?  
2. Can you confirm that your storage account is set in the accountName field in the notebook?
3. Can you confirm that you have the FlighjtsAndWeather.csv file at wasbs://sparkcontainer@{your storage account}.blob.core.windows.net/FlightsAndWeather/2017/03/FlightsAndWeather.csv?

**Comment by aniturza** [comment]
1. When you set up the windowStart parameter on ADF, can you confirm that it's "3/1/2017"? Yes, I confirm
2. Can you confirm that your storage account is set in the accountName field in the notebook? Yes, I confirm
3. Can you confirm that you have the FlighjtsAndWeather.csv file at wasbs://sparkcontainer@{your storage account}.blob.core.windows.net/FlightsAndWeather/2017/03/FlightsAndWeather.csv? Yes, I confirm

The error appears at the end of the notebook,  when storing the table with `prediction.write.mode("overwrite").saveAsTable("scoredflights")` . The error is the same when running manually and from ADF

**Comment by feaselkl** [comment]
I think I have a lead on what's happening but will need to investigate further.  I should have a potential answer tomorrow.

**Comment by aniturza** [comment]
Thank you @feaselkl , I look forward to it!

**Comment by feaselkl** [comment]
The error is coming from a StringIndexer failure in converting from string to double.  In the exercise 5 notebook, could you run the following and paste the results?

`dfDelays`

You should see an Out line which shows the DataFrame structure.  Then,

`dfDelays.show(10)`

Finally, I'm expecting an error if you run the following:

`prediction.display(10)`

**Comment by aniturza** [comment]
Here my results:

`dfDelays` --> Correct output

`dfDelays.count() `--> 3132106

`dfDelays.show(10)` --> Correct output

`dfDelays.select('DepDel15').distinct().show(truncate=False) `

+--------+
|DepDel15|
+--------+
|null    |
+--------+

`prediction.display(10)` --> AttributeError: 'DataFrame' object has no attribute 'display'

**Comment by feaselkl** [comment]
These results aren't correct.  The ADF pipeline that you've set up should only have retrieved one month's worth of data for 861324 results.  Furthermore, DepDel15 should have two values:  0 and 1.

Please download the file that the script points to (specifically, FlightsAndWeather/2017/3/FlightsAndWeather.csv) from your storage account's sparkcontainer container and paste the first 3 rows from that file as you see them.

Also, please paste the directory listing on your Integration Runtime VM for 2017-03 flights and weather.  For example, D:\Something\Something\Something\FlightsAndWeather\2017\03.

Then, in Azure Data Factory, navigate to Manage --> Linked services (in the Connections) menu and select OnPremServer.  What is the Host directory?

**Comment by aniturza** [comment]
Blob Storage FlightsAndWeather.csv top 3 rows

AIRPORT_ID,AIRPORT,DISPLAY_AIRPORT_NAME,LATITUDE,LONGITUDE						
10001,"01A","Afognak Lake Airport","58.10944444","-152.9066667"						
10003,"03A","Bear Creek Mining Strip","65.54805556","-161.0716667"						

C:\Users\aniturza\Downloads\FlightsAndWeather\FlightsAndWeather\2017\03

Host Directory in ADF: C:\

**Comment by aniturza** [comment]
OriginAirportCode,Month,DayofMonth,CRSDepHour,DayOfWeek,Carrier,DestAirportCode,DepDel15,WindSpeed,SeaLevelPressure,HourlyPrecip				
SEA,"4","19","21","5","WN","SMF","1","9","30","0"				
ORD,"3","9","9","3","UA","LAS","0","5","30","0"				

C:\Data\FlightsAndWeather\2017\03

C:\Data

I re-run the previous and now I get `861324 `results and : 

```
+--------+
|DepDel15|
+--------+
|1       |
|0       |
+--------+
```

`prediction.display(10)` --> AttributeError: 'DataFrame' object has no attribute 'display'

**Comment by feaselkl** [comment]
Okay.  With those results, you should be able to strip out the  elements I added (ignoring the prediction.display bit), getting those results and having the correct departure delay values, the process should now work.  Based on what you were showing, the old FlightsAndWeather.csv was actually airport codes based on your comment above.

**Comment by aniturza** [comment]
@feaselkl Thank you! Now it all works!
